FROM registry.access.redhat.com/ubi10/go-toolset:latest AS builder

USER root

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY main.go ./

RUN go mod tidy && go build -o guestbook-api .

FROM registry.access.redhat.com/ubi10-minimal:10.0

WORKDIR /app

COPY --from=builder /app/guestbook-api .

EXPOSE 8080

CMD ["./guestbook-api"]
